#!/bin/bash

if [[ $1 == upgrade ]]; then
/bin/launchctl unload /Library/LaunchDaemons/com.tyc.tcscan.plist
killall GameGemPro
killall MemSearch
killall _MemSearch
fi

chown root:wheel /usr/bin/tcscan
chmod 755 /usr/bin/tcscan
chown root:wheel /Library/LaunchDaemons/com.tyc.tcscan.plist
chmod 644 /Library/LaunchDaemons/com.tyc.tcscan.plist


chown root:wheel /Applications/MemSearch.app/_MemSearch
chown root:wheel /Applications/MemSearch.app/MemSearch

chmod 0755 /Applications/MemSearch.app/_MemSearch
chmod 4755 /Applications/MemSearch.app/MemSearch



killall GameGemPro
killall MemSearch
killall _MemSearch

#/usr/bin/uicache

/bin/launchctl load /Library/LaunchDaemons/com.tyc.tcscan.plist


exit 0

