#!/bin/bash

declare -a cydia
cydia=($CYDIA)

case "$1" in
  upgrade)
    if [[ ${CYDIA+@} ]]; then
        echo "Killing GameGemPro process..."
        killall GameGemPro
        killall MemSearch
        killall _MemSearch
    fi
  ;;
esac

exit 0
